// <auto-generated />
using System;
using EquipmentBorrowing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentBorrowing.Infrastructure.Migrations
{
    [DbContext(typeof(EquipmentBorrowingDbContext))]
    [Migration("20261003193826_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("EquipmentBorrowing.Domain.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpectedReturnOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("StudentId", "Status");

                    b.ToTable("Borrowings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Borrowings_DueAfterBorrowed", "ExpectedReturnOn > BorrowedOn");

                            t.HasCheckConstraint("CK_Borrowings_StatusMatchesReturnedOn", "(Status = 'Active' AND ReturnedOn IS NULL) OR (Status = 'Returned' AND ReturnedOn IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorrowedOn = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EquipmentId = 5,
                            ExpectedReturnOn = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 2,
                            BorrowedOn = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EquipmentId = 6,
                            ExpectedReturnOn = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 3,
                            BorrowedOn = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EquipmentId = 7,
                            ExpectedReturnOn = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            BorrowedOn = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EquipmentId = 8,
                            ExpectedReturnOn = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 5,
                            BorrowedOn = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EquipmentId = 4,
                            ExpectedReturnOn = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedOn = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            StudentId = 1
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Equipment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Name = "HDMI Projector",
                            Type = "Audio Visual"
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = true,
                            Name = "Laptop",
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = true,
                            Name = "Extension Cord",
                            Type = "Accessory"
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = true,
                            Name = "Speaker",
                            Type = "Audio Visual"
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = false,
                            Name = "Laptop 02",
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = false,
                            Name = "Camera",
                            Type = "Photography"
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = false,
                            Name = "Tripod",
                            Type = "Photography"
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = false,
                            Name = "Microphone",
                            Type = "Audio Visual"
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAllowedToBorrow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAllowedToBorrow = true,
                            Name = "Dodong",
                            StudentNumber = "2023-0001"
                        },
                        new
                        {
                            Id = 2,
                            IsAllowedToBorrow = true,
                            Name = "Ana Reyes",
                            StudentNumber = "2023-0002"
                        },
                        new
                        {
                            Id = 3,
                            IsAllowedToBorrow = true,
                            Name = "Ben Santos",
                            StudentNumber = "2023-0003"
                        },
                        new
                        {
                            Id = 4,
                            IsAllowedToBorrow = false,
                            Name = "Carla Mendoza",
                            StudentNumber = "2023-0004"
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Borrowing", b =>
                {
                    b.HasOne("EquipmentBorrowing.Domain.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EquipmentBorrowing.Domain.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
